### ISSUE TITLE
Playing inncorrect songs while in artist view

### ISSUE THREAD

**Issue by szaszlyki21** [rasmuslos/AmpFin#10]
Probably a bug, while in artist view pressing the play icon plays songs from the whole jellyfin library, not the artist's catalog

https://github.com/rasmuslos/AmpFin/assets/96011540/01f9307a-2dad-4e8e-86a4-33ea57c8c85f

**Comment by rasmuslos** [comment]
The play button plays the artist instant mix, I could not find any reliable sources on how it works (other than look at the source code I guess). A solution could be to add an extra button for just the artist mix

**Comment by rasmuslos** [comment]
I have added an instant mix toggle to the settings, playing only songs from the artist is now the default behavior
