### ISSUE TITLE
Third-party lyrics

### ISSUE THREAD

**Issue by JimmyJichi** [rasmuslos/AmpFin#14]
Instead of waiting for official lyrics support, should we consider getting lyrics from third party services instead? [LRCLIB](https://lrclib.net/) provides a simply and free API that seems to be perfect for something like this.

**Comment by rasmuslos** [comment]
Lyrics are copyrighted works, so as much as I like lrclib, I am not quite sure if the service they are proving is actually legal. And even if no one can really enforce this, I still highly doubt that apple will allow this to slip through app review.
