### ISSUE TITLE
Does this project have Testflight?

### ISSUE THREAD

**Issue by weiyideai520** [rasmuslos/AmpFin#15]
Unfortunately, I don't have a Mac computer. Is Testflight available for use?

**Comment by rasmuslos** [comment]
I have purchased an apple developer program membership and plan on selling the app through the App Store, but I will not publicly distribute it through TestFlight. It is stuck in review (and has been for about two months) for now. Apps that are available though a public TestFlight are also required to be reviewed, so there is no point in doing one to bridge the time
