### ISSUE TITLE
Can’t connect to remote IP

### ISSUE THREAD

**Issue by fabk** [rasmuslos/AmpFin#20]
Hi,

I can not connect to a remote IP. 192.168.x.x works, 100.x.x.x doesn’t. I can connect to 100.x.x.x through Safari, the Jellyfin app and Manet. AmpFin says it couldn’t find the server.

is there a way to connect to remote addresses?

Thank you

**Comment by rasmuslos** [comment]
Hey,

is the protocol correct? Also are you using Tailscale? Someone reported a similar issue with ShelfPlayer, so this might be related.

**Comment by rasmuslos** [comment]
And did you get the iOS "Allow connections to you local network" promt?

**Comment by fabk** [comment]
Hi,

thank you for the reply. I am using Tailscale and didn’t get a prompt when starting the app.

**Comment by rasmuslos** [comment]
Can you try inputting 192.168.1.1 and going a step further. Maybe 100.x.x.x addresses are considered part of the local subnet. The other address _should_ trigger the dialog.

**Comment by rasmuslos** [comment]
Can you provide the Tailscale debug logs (they can be created in the Tailscale app)

**Comment by rasmuslos** [comment]
See https://github.com/rasmuslos/ShelfPlayer/issues/55#issuecomment-1997406321
