### ISSUE TITLE
Add support for a singles

### ISSUE THREAD

**Issue by PauFCB** [rasmuslos/AmpFin#23]
In my music folder I have some individual singles that don't belong to any album. I can add these items to a playlist, play and download with all clients (Desktop, fintunes, finamp etc) but not with this app, I even can't see the song in the playlist. Thanks

**Comment by rasmuslos** [comment]
Are these singles in an album just for the single or are these just songs without any parent?

**Comment by PauFCB** [comment]
> Are these singles in an album just for the single or are these just songs without any parent?

Are individual aac, mp3 and some flac songs out of any album, on the main root music folder next to the artists folders. But the metadata it's edited with the app Meta and mp3tag for MacOS. And as I said, appears on the other clients and web. Thanks! Just bought the app btw.

**Comment by rasmuslos** [comment]
The code assumes that each track is part of an album in a lot of places, so this might not be so easy. Is it an option to create a album for each single, like the major streaming services or musicbrainz do?

**Comment by rasmuslos** [comment]
> > The code assumes that each track is part of an album in a lot of places, so this might not be so easy. Is it an option to create a album for each single, like the major streaming services or musicbrainz do?
> 
> Yes, in order to that song appears on the clients ai have to put on a folder, but If add that song to a playlist it doesn't matter

It still does not work because other things like cover art is still dependent on an album

**Comment by PauFCB** [comment]
I'd try to create a "fake" folder for every track and see if it works

**Comment by PauFCB** [comment]
Solved, for one interested: put every single on a folder, doesn't matter the title. After that you can individywlly set a cover for each song one by one.

**Comment by rasmuslos** [comment]
> Solved, for one interested: put every single on a folder, doesn't matter the title. After that you can individywlly set a cover for each song one by one.

That is really strange, but good to hear that it works!
