### ISSUE TITLE
OPUS and Vorbis files cannot be played.

### ISSUE THREAD

**Issue by freedompath** [rasmuslos/AmpFin#25]
When trying to play Opus or Vorbis files, the program skips to the next Mp3 file and only plays this file. However, the Vorbis or Opus titles and covers are displayed when the Mp3 file is played.

**Comment by freedompath** [comment]
Ah I understand! Thank you very much for your quick response!

**Comment by rasmuslos** [comment]
Also i forgot to update the download logic, but this has been resolved. If you download the tracks that have to be transcended they will now be saved as an `aac` file. For local files the duration is correct.
