### ISSUE TITLE
Album Artist route error 

### ISSUE THREAD

**Issue by PauFCB** [rasmuslos/AmpFin#26]
Hi, I like to edit artists bios, photos and metadata on desktop app.
But using Ampfin, I can only see these changes updated if I go to the specific Artist thru now playing screen, but not if I go to Artists or Album Artists from home screen options. 
Thanks

**Comment by rasmuslos** [comment]
AmpFin fetched artists in the list view, not the actual artist view. So you have to go back to the library view for you changes to take effect. The next update adds the pull to refresh gesture to the artist list view.
