### ISSUE TITLE
Estonian App Store app availability

### ISSUE THREAD

**Issue by iamironz** [rasmuslos/AmpFin#36]
I understand that currently, the app is not available on the Estonian (or, probably across the globe or even de-listed) App Store. 
When attempting to access the app, a generic error message appears, and even opening the app from the "installed app" directory in the iOS App Store shows that something went wrong. 
I wanted to confirm if you are already aware of this issue.

**Comment by gnattu** [comment]
This is made intentionally atm, as rasmuslos is not decided whether to make this app free in the future. To minimize impact, this app is currently made unavailable for purchase.  

You can see the discussion here, starting from this comment: https://github.com/rasmuslos/AmpFin/pull/34#issuecomment-2053951215

**Comment by iamironz** [comment]
I will follow this topic closely and hope for a dedicated thread in the future to ensure transparency for users and contributors. 
Thank you for the clarification.

**Comment by rasmuslos** [comment]
The app is still paid, so everything will remain as is. You should be able to see the store page again in a few hours.
