### ISSUE TITLE
Quality of life improvements

### ISSUE THREAD

**Issue by mvastum** [rasmuslos/AmpFin#38]
Hi rasmuslos,

thank you for this great app first of all! I've been using it daily since release and it's only gotten better and better. I've noticed a few minor details that could be improved though. 

1 Tapping the "Bibliothek" button should bing me back to home everytime I tap it. Another tap should scroll to the top of the page if I'm not already there. 

2 Tapping "Suche" once should open the search tab (as is) and a second tap should open the keyboard. Both these features can be seen in the stock App Store app with the tabs "Heute" and "Suche" accordingly if it's not clear from my description. 

3 In the Playlist View the Cover of the Playlist is not shown, just a blurred out version of it. In the Artist View the picture is displayed correctly. Is this intentional or are there any limits for uploading your own covers for playlists?

4 Is it possible to implement an alphabet picker in the (album-) artist overview? The scrolling bar is nice to have but much too imprecise to get to certain letters fast. 

5 Lastly I believe that shuffling my favorites doesn't pick up all songs from my favorites, just maybe around the most recent 200 songs or so. I have more favorited songs than that, is there a limit as to how many songs are being shuffled?

Thank you again for developing this app, I'm curious to see, what will come in the future!

Cheers

mvastum

**Comment by rasmuslos** [comment]
Regarding 1 & 2: Not possible in SwiftUI, I am going to a Apple Vision Pro lab in a few weeks, I will ask the engineers there, but I am pretty sure that there is no way to do that (in SwiftUI).

It is intentional that the cover is not shown, but adding a toggle might be a good idea.
The picker has as similar problem as 1 & 2, it is not possible to do it in a _good_ way.

From my experience SwiftUI has many of these shortcomings, it is extremely annoying...

The last one is related to lazy loading, but requesting a randomly sorted selection from Jellyfin should fix it.

**Comment by mvastum** [comment]
Thank you for your quick reply - that's unfortunate and kinda strange, that apple doesn't allow implementation of its own UI features in swift. Anyway, it won't take away from the joy the app brings!

Cheers,

mvastum

**Comment by rasmuslos** [comment]
👍 

I am by now convinced they just do it for fun and to spite developers. Here is a non exhaustive list of my favorite private implementations:

- WatchOS now playing queue & chapters
- Now playing widget suggestions
- Journaling suggestions (they essentially paywalled a mental health feature behind a 10$ apple music subscription, kind of unethical in my opinion)
- The tab bar thing
- Volume picker on visionOS
- Some sort of sheet used for the now playing animation (it pushes the content back but somehow exists in the "space")

**Comment by rasmuslos** [comment]
Also they use custom audio players for e.g. Apple Music, its a bit weird they they would invest in creating a second audio player instant of making `AVPlayer` better (there is still no equalizer, but apple music has one)
