### ISSUE TITLE
large playlist downloads fail

### ISSUE THREAD

**Issue by hungl6844** [rasmuslos/AmpFin#40]
when trying to download my playlist, which is ~600 songs, the ui freezes, and eventually the player crashes. after reopening the app, all of the songs are stuck in a state where the app thinks they’re being downloaded, but no download is actually taking place, stopping me from re-queuing the download.

**Comment by hungl6844** [comment]
update: after some waiting, I was able to download my library, but the UI remained incredibly unresponsive, and if I had tried to stream a song, or use the app significantly during that time period, it likely would have crashed.

**Comment by rasmuslos** [comment]
If have not looked into the download thing yet, but the performance could be drastically improved by not queueing all tracks into the AVQueuePlayer, only a few that are coming up.

**Comment by rasmuslos** [comment]
https://github.com/rasmuslos/AmpFin/commit/428d860ada2af5d0b8c94959909e111b90965d25 should improve playback performance and both downloading and playing large collections should now work.
