### ISSUE TITLE
Some audio tracks do not appear on app

### ISSUE THREAD

**Issue by skellycode** [rasmuslos/AmpFin#46]
Some of the audio tracks in my music library do not appear in the app (missing from search, playlists, etc).
Yet they are present in the Jellyfin WebUI/Fintunes/Finamp/etc.

How can I provide relevant information to help with this bug report?

**Comment by rasmuslos** [comment]
Tracks that lack an album are filtered out. Can you verify that the tracks are properly imported in Jellyfin and have an associated album.?

**Comment by skellycode** [comment]
That explains it!
Why do tracks with no album get filtered out?  Can this be fixed?

**Comment by rasmuslos** [comment]
Tracks belong to an album, it's a design decision, not necessary a bug. Having singles is fine, but the songs still belong to an album. I noticed some wonky behavior in Jellyfin when a song is missing its album, so I assumed this happens when a song cannot be imported properly.

**Comment by skellycode** [comment]
I strongly disagree with this.  This precludes the ability for users to be able to stream audio files from their Jellyfin server that may not necessarily be part of an album or any official release.  In my example: home-recorded audio clips of my children singing, or random rips of audiobooks for the kids to listen to.
This is also particularly problematic for those with large, somewhat poorly organised media directories where the amount of “un-albumed” tracks is a gross unknown.
I have had no issues with other players (such as FinTunes) for tracks without albums - however FinTunes (and others) have their own issues.  It feels like a bit of a sad state to have to choose between a nice UI (AmpFin) at the expense of being able to play the media on my server.  Why should the app be the gatekeeper?

I appreciate the effort put into this app (shown by my purchase of AmpFin via the App Store), and strongly urge you to reconsider :)

**Comment by rasmuslos** [comment]
The problem is that the entire download logic is based on the assumption that tracks have a parent. It is of course possible to change this, but it would require significant effort. I will look into this but I won't promise anything and this will not be changed in the near future, because of the big amount of time this will take. But I found the relevant Jellyfin issue, if you want to have a look at it: https://github.com/jellyfin/jellyfin/issues/1757
