### ISSUE TITLE
1.4.4 broke AmpFin on iPhone 14 Pro

### ISSUE THREAD

**Issue by lemonlimelabs** [rasmuslos/AmpFin#51]
I can no longer access any of the music on my server through AmpFin except tracks after the 1.4.4 update. Albums, Album Artists, Artists, and everything other than Tracks says content unavailable with an X in a circle. I can browse and listen through the Tracks navigation so I know I’m connected properly. I’ve deleted the app, redownloaded and reconnected to my server with the same results. Everything worked for me prior to this update.

**Comment by rasmuslos** [comment]
Can you try connecting to the Jellyfin demo instance at `https://demo.jellyfin.org/stable` (username: `demo`, blank password) and see if everything works? What Jellyfin version are you using?

**Comment by lemonlimelabs** [comment]
Connecting to the demo worked great. My Jellyfin version is 10.8.12.

**Comment by lemonlimelabs** [comment]
Okay upgraded my Jellyfin version to 10.9.6 and this fixed the issue. Please take not anyone who is having trouble that you should upgrade your Jellyfin version to the newest available.

**Comment by rasmuslos** [comment]
Theoretically AmpFin should still be compatible with 10.8 instances, but if upgrading resolved the issue for you, great
