### ISSUE TITLE
A non-Jellyfin, completely offline build of AmpFin

### ISSUE THREAD

**Issue by LuckyTheCoder** [rasmuslos/AmpFin#59]
I don’t use Jellyfin but really dig this UI. Is there a way to create a build w/o Jellyfin?

**Comment by rasmuslos** [comment]
Not really, no. The app only makes requests to your Jellyfin instance. You can edit the `JellyfinClient` or `OnlineLibraryDataProvider` as well as `LocalAudioEndpoint+Helper` & `DownloadManager+Helper` to change the data source but it don't think that's an easy task. The app is designed around Jellyfin and the way it works...
