### ISSUE TITLE
Re:incorrectly showing artists when artist.seperator is used

### ISSUE THREAD

**Issue by szaszlyki21** [rasmuslos/AmpFin#6]
Unfortunately, the issue still persist in the latest update. I've checked with the official client just to be sure and yes it does show the artists correctly on the ios client.
![IMG_2544](https://github.com/rasmuslos/AmpFin/assets/96011540/ae2c64e9-f816-44e5-8b99-5245e4bc885d)
![IMG_2545](https://github.com/rasmuslos/AmpFin/assets/96011540/64c37320-9552-4517-8537-42d5bfbaa00c)

**Comment by rasmuslos** [comment]
Sorry, it is truly beyond me why the previous fix didn't work, for now I have just hardcoded the comma https://github.com/rasmuslos/AmpFin/releases/tag/v1.0.10
