### ISSUE TITLE
Equalizer?

### ISSUE THREAD

**Issue by Badraraa676** [rasmuslos/AmpFin#7]
Hey! Is there an Equalizer in this app? If not, could u please add one? I love love love love looooove the design and I'd love an Equalizer too! Keep up the good work tho!!

**Comment by Badraraa676** [comment]
I can't open the app after sideloading it on iOS 16.

**Comment by rasmuslos** [comment]
Well the app is build using the iOS 17 SDK so this is expected behavior. How are you logging in, using the local strategy or sso?

**Comment by rasmuslos** [comment]
Thanks! There is no equalizer right now and it might take some time util it is introduced because the AVQueuePlayer (provided by Apple) that the app uses under the hood does not have equalizer functionality. I would either have to write my own implementation or use a third party one.
