### ISSUE TITLE
Tracks not loading

### ISSUE THREAD

**Issue by Ixeonindustries** [rasmuslos/AmpFin#79]
Hello there!
Im having an issue with my Iphone. 
Non of the tracks are loading. They are visible but only as a Placeholder (No title, no artist)
I checked with the demo website (https://demo.jellyfin.org/stable) and it did work.
Trying with the local IP did not work aswell.
Am I doing something wrong @rasmuslos ?

Kind regards,
Xeon

**Comment by Ixeonindustries** [comment]
![Ampfin](https://github.com/user-attachments/assets/3a130d4a-b12e-4402-90ac-a3b9a3db895c)

This is what Im getting when trying to play music

**Comment by theMackabu** [comment]
I'm having the same issue![image](https://github.com/user-attachments/assets/5388229c-ce6e-46b1-84a1-7d2041392fbe)
![image](https://github.com/user-attachments/assets/394eac74-e35f-4191-ac59-dd6137c0829e)

**Comment by rasmuslos** [comment]
What version of Jellyfin & AmpFin are you using? Can you post a screenshot of one of your albums in the web interface?

**Comment by theMackabu** [comment]
<img width="789" alt="Screenshot 2024-10-18 at 2 03 23 PM" src="https://github.com/user-attachments/assets/ba241691-af48-4084-b3b3-d6a20f497d57">
<img width="1385" alt="Screenshot 2024-10-18 at 2 03 39 PM" src="https://github.com/user-attachments/assets/641986bf-05b1-4b64-86a6-830248270207">

**Comment by rasmuslos** [comment]
Are these singles associated with an album?

**Comment by theMackabu** [comment]
> Are these singles associated with an album?

There are no albums at all in this media library

**Comment by theMackabu** [comment]
If that's a requirement I can migrate to albums

**Comment by theMackabu** [comment]
Switching to album based tree fixed the issue for now
<img width="374" alt="Screenshot 2024-10-18 at 5 49 59 PM" src="https://github.com/user-attachments/assets/d7bf85ee-48be-40a8-8006-8de51fa36691">

**Comment by Ixeonindustries** [comment]
I also have not a single album in my library. Only single media. 
Are albums required in order to play media on the app, or is it just a coincidence that it started to work for Mack?

**Comment by theMackabu** [comment]
I think albums are required, I did it manually

> > Switching to album based tree fixed the issue for now
> > <img alt="Screenshot 2024-10-18 at 5 49 59 PM" width="374" src="https://private-user-images.githubusercontent.com/32078755/378037612-d7bf85ee-48be-40a8-8006-8de51fa36691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjQ3NzYsIm5iZiI6MTcyOTMyNDQ3NiwicGF0aCI6Ii8zMjA3ODc1NS8zNzgwMzc2MTItZDdiZjg1ZWUtNDhiZS00MGE4LTgwMDYtOGRlNTFmYTM2NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA3NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYmI5ZjlkOWJjZDc3MWVlZWNmNjU3N2IzNjQ3YjJiYjc5YzhiODZjNGRmOTI5OGRjNWRjMmI4N2MxNzE3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RFZ9UKc5flllohcufH7XXLJsKAoozOVZkeLELqgql4E">
> 
> Also... is there a quick way to switch to an album based tree, or did you do this manually?

**Comment by Ixeonindustries** [comment]
I apologise for the delayed reply.
Creating albums solved the issue.
I appreciate the help!

Regards,
Erick

**Comment by rasmuslos** [comment]
Sorry for the even later reply...

AmpFin (and all other major music apps I can think of) is (are) currently designed around the assumption that every track has a parent album. I want to resign some aspects of AmpFin and may change this, but this will take some time.
