### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by michaelhthomas** [rasmuslos/AmpFin#8]
This project looks really great, and I'd love to use and contribute to it, but it's difficult to do so legally without a license. 

Check out https://choosealicense.com for some helpful advice on the license to choose.

**Comment by rasmuslos** [comment]
Thanks a lot!

I know that the app is not open source, only source available, right now, and I intent to change that, but only after the AppStore release. Also I am not quite sure of the legal implications of having other contributors, especially when the app is published on the AppStore.
But until I figure this stuff out, what would you like to see added? Playlist support is the only thing that is stopping me from putting the app on the AppStore, so it is on the roadmap, but a lot of the download code has to be rewritten for this to work.

**Comment by rasmuslos** [comment]
I think the Mozilla Public License 2.0 is the best choice, it allows distribution on the AppStore (unlike GPL) but still ensures that the source code remains open source

**Comment by michaelhthomas** [comment]
> But until I figure this stuff out, what would you like to see added? Playlist support is the only thing that is stopping me from putting the app on the AppStore, so it is on the roadmap, but a lot of the download code has to be rewritten for this to work.

Playlist support is a big one for me, but apart from that, there's nothing super pressing. Thanks for looking into the licensing stuff, MPL sounds great1

**Comment by rasmuslos** [comment]
Are you able to install the 1.1.1 (playlist support) release? It seems to crash without any reason when sideloading

**Comment by rasmuslos** [comment]
The project is now licensed under MPL v2
