### ISSUE TITLE
Compatibility for iOS 15

### ISSUE THREAD

**Issue by slimjet4u** [rasmuslos/AmpFin#81]
The Ampfin is good, I was wondering if can be made compatible for ios 15

**Comment by gnattu** [comment]
I don't think so. This app aggressively uses iOS API that is only available in edge version of iOS.  For example, the data backend, the swiftdata is only available on iOS 17.0+

**Comment by rasmuslos** [comment]
Exactly. SwiftUI becomes more and more unusable the further you go back, too.
