### ISSUE TITLE
How to install the ipa? I can't with Xcode or iMazing

### ISSUE THREAD

**Issue by PauFCB** [rasmuslos/AmpFin#9]
Hi, can you please give more detailed steps to install the ipa?
Love the screenshots, btw I have a suggestion: Big artist posters with a collapsed bio description.
Thanks

**Comment by rasmuslos** [comment]
There are some instructions in the Readme, I am planning on making them more detailed in the future

The artist page has been reworked, the list view may get updated in the future

<img width="390" alt="Bildschirmfoto 2023-12-27 um 13 14 47" src="https://github.com/rasmuslos/AmpFin/assets/49640416/43cae105-8761-43b8-9464-81cde1dcb6eb">

**Comment by PauFCB** [comment]
Just installed the app (finally🙏🏻) but using the app Scarlet, having to install a certificate.. Just LOVING your app! I hop that soon will be able to install it via TestFlight or something more secure, and can't wait to test the new improvements for the artist view, metadata and playlists!
Happy new year and keep the good work. (I'd be happy to pay a one time fee when the app launch officially).
Thanks

**Comment by rasmuslos** [comment]
Thanks!
I will publish the App after I get around to add playlist support, the problem is that I have to rewrite a big part of the download logic for that, a quite tedious task
